apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-energy-test-ingress
  namespace: test-temp
spec:
  ingressClassName: nginx
  rules:
    - host: simpleenergy.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-energy-test-service
                port:
                  number: 5000              # Must match service targetPort


